### ISSUE TITLE
If node is not installed in the machine, it doesn't start up

### ISSUE THREAD

**Issue by menduz** [decentraland/editor-sdk6#24]
To met the criteria of lowering the entry barrier, setups without node js should be allowed OOTB.

To replicate the environment, open a terminal without NVM and other node installations and execute `code` to not have it registered in the PATH env var.

![Screen Shot 2022-11-07 at 22 01 42](https://user-images.githubusercontent.com/260114/200448592-934f785c-02ce-4eec-9bf7-4481e969a318.png)

**Comment by cazala** [comment]
mm node is already installed within vscode right? Since that's how the extension itself is run. Should we try to use those binaries (ie set the $PATH to where they are?)

**Comment by menduz** [comment]
It should be installed but neither `node` or `npm` are resolvable if not present in $PATH
